spring.application.name=Smart_Traffic_Flow

# Configuracoes do Banco H2
spring.datasource.url=jdbc:h2:mem:smarttraffic;NON_KEYWORDS=DATABASE,TABLE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# Estrategia do Hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Garante que o script SQL espere a criacao das tabelas pelo Hibernate
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Logs e Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Performance
spring.jpa.open-in-view=false
